# Generated by Django 4.1.5 on 2023-11-02 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwords',
            unique_together={('user', 'first_word', 'second_word')},
        ),
    ]
