# Generated by Django 4.1.5 on 2023-11-02 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userwords_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwords',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userwords',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
